spring:
  profiles:
    active: dev-6868
    
---
#服务器启动的时候所占用的端口
server:
  port: 6868
  
spring:
  profiles: dev-6868
  application:
    name: eureka-server
  security:
    user:
      name: navy
      password: 123456
    
eureka:
  instance:
    hostname: localhost
  client:
  #   是否开始注册服务，因为我自己就是一个注册服务器，并且不需要向其他注册服务器注册，所以改成false
    registerWithEureka: false   #如果要注册到集群中需要改成true
    #是否拉取服务列表，这里我只提供服务给别的服务器
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
  
  server:
    enable-self-preservation: false #关闭自我保护
    
---
server:
  port: 6869
  
spring:
  profiles: dev-6869
  application:
    name: eureka-server
  security:
    user:
      name: navy
      password: 123456
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   #如果要注册到集群中需要改成true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
  
  server:
    enable-self-preservation: false #关闭自我保护
      